# Generated by Django 5.2 on 2025-04-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0004_alter_article_reading_time_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The name of the category (e.g., 'Web Development', 'LLM').", max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='A URL-friendly slug for the category.', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
    ]
