# Generated by Django 5.2 on 2025-04-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Select one or more categories for this article.', related_name='articles', to='curation.category'),
        ),
    ]
